sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
  - clang
env:

  global:
    - CMAKE_GENERATOR="Unix Makefiles"
    - CMAKE_DEPS_BUILD_TYPE=Release
    - GTEST_BUILD_TYPE=Release
  matrix:
    - CMAKE_BUILD_TYPE=Release SGFXAPI_BUILD_TYPE=Release
    - CMAKE_BUILD_TYPE=Debug SGFXAPI_BUILD_TYPE=Debug


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
    - set -exv
    - cmake --version
    - gcc --version
    - clang --version
    - mkdir -p build && cd build
    - cmake -G "$CMAKE_GENERATOR" .. -DCMAKE_VERBOSE_MAKEFILE=1
    - cmake --build .
    
    - cd ../


